/**
 * Single guarded entry point for registering the app's service worker.
 *
 * The SW is generated by `vite-plugin-pwa` (injectManifest strategy) and is
 * emitted at `/app-runtime-sw.js`. It enables offline boot of the driver
 * panel (and the rest of the app) by caching the app shell + assets.
 *
 * We MUST NOT register in dev, in Lovable preview, inside an iframe, or via
 * the `?sw=off` kill-switch. In any of those cases we also unregister any
 * matching stale SW so users don't get stuck on an old cached build.
 */
import { shouldDisableServiceWorker } from "@/lib/appRefresh";

const SW_URL = "/app-runtime-sw.js";
const SW_SCOPE = "/";
const KILL_SWITCH_PARAM = "sw";

const LEGACY_SW_PATHS = ["/sw.js", "/app-sw.js"];

async function unregisterMatching(): Promise<void> {
  if (!("serviceWorker" in navigator)) return;
  try {
    const registrations = await navigator.serviceWorker.getRegistrations();
    await Promise.all(
      registrations.map(async (reg) => {
        const scriptUrl = reg.active?.scriptURL || reg.installing?.scriptURL || reg.waiting?.scriptURL || "";
        try {
          const path = new URL(scriptUrl, window.location.origin).pathname;
          if (path === SW_URL || LEGACY_SW_PATHS.includes(path)) {
            await reg.unregister();
          }
        } catch {
          // ignore parse errors
        }
      }),
    );
  } catch (e) {
    console.warn("[SW] unregister sweep failed", e);
  }
}

export async function registerAppServiceWorker(): Promise<void> {
  if (!("serviceWorker" in navigator)) return;

  const killSwitch = new URLSearchParams(window.location.search).get(KILL_SWITCH_PARAM) === "off";

  if (shouldDisableServiceWorker() || killSwitch) {
    await unregisterMatching();
    return;
  }

  try {
    await navigator.serviceWorker.register(SW_URL, { scope: SW_SCOPE });
    // Quietly remove any legacy worker registrations to avoid duplicates.
    await Promise.all(
      LEGACY_SW_PATHS.map(async (path) => {
        try {
          const reg = await navigator.serviceWorker.getRegistration(path);
          if (reg) await reg.unregister();
        } catch {
          // ignore
        }
      }),
    );
  } catch (e) {
    console.warn("[SW] register failed", e);
  }
}
